# Generated by Django 3.0.6 on 2020-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('islamic', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('behavior', models.BooleanField()),
                ('friend1', models.IntegerField()),
                ('friend2', models.IntegerField()),
                ('friend3', models.IntegerField()),
                ('friend4', models.IntegerField()),
                ('friend5', models.IntegerField()),
            ],
        ),
    ]
