# Generated by Django 3.0.6 on 2020-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_maker', '0002_auto_20200601_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
    ]
